### ISSUE TITLE
Cambiar logo en top navbar con el Logo de LET + ITESM

### ISSUE THREAD

**Issue by zoek1** [civica-digital/let#10]

**Comment by juanpabloe** [comment]
![uploads/a7a6765b-8453-426d-a123-2fd19f952589/logo-let-tec.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa7a6765b-8453-426d-a123-2fd19f952589%2Flogo-let-tec.png)

**Comment by juanpabloe** [comment]
Creo que no se ve bien como quedó al final este logo... Reabro para trabajar un workaround

**Comment by juanpabloe** [comment]
Posiblemente hagamos el logo con un height más alto
