### ISSUE TITLE
Cambiar logo Escuela 

### ISSUE THREAD

**Issue by GlendaMi** [civica-digital/let#35]
Hey necesito que en la barra de inicio se cambie el logo de la Escuela de Gobierno a sus colores originales porfa porque cuando la barra cambia a blanco no se puede que el logo sea gris. Y que sea más grande (del mismo tamaño que el del LET)

Gracias!

**Comment by juanpabloe** [comment]
@zoek1 acá no se ve bien al mero inicio cuando está en background transparente:

![uploads/ce88b319-4e93-4b1f-94b2-979f00e98997/Screen Shot 2015-06-02 at 1.12.07 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fce88b319-4e93-4b1f-94b2-979f00e98997%2FScreen+Shot+2015-06-02+at+1.12.07+PM.png)

ves posible iniciar con la versión en gris y cuando se hace scroll y transiciona el background a blanco modificar por el otro logo?
