### ISSUE TITLE
/mecate/

### ISSUE THREAD

**Issue by juanpabloe** [civica-digital/let#5]
- [x] Vista con el puro logotipo y que explique que es mecate.
- [x] hay que crear un typeform y embeberlo.
- [x] desde la vista de /mecate/ el top navbar debe ser diferente.

**Comment by juanpabloe** [comment]
@zoek1 hay que crear un [typeform](http://typeform.com) y embeberlo

**Comment by juanpabloe** [comment]
@zoek1 desde la vista de /mecate/ el top navbar debe ser diferente:
- Inicio (/)
- Mecate (/mecate/)

No debería tener toda la navegación del landing

**Comment by zoek1** [comment]
Tenia la duda en eso, a cambiarlo entonces.
